[package]
name = "schemarefly-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
schemarefly-core.workspace = true
schemarefly-dbt.workspace = true
serde = { version = "1.0", features = ["derive"] }
